export const TECHNOLOGY = [
  {
    name: "Weather site",
    technologies: ["React", "Typescript", "React-query", "SCSS module", "Vite"],
    link: "https://denisfriz.github.io/Weather-site/",
    smallImg: "./img/Weather-main.JPG",
    fullscreenImg: "./img/Weather-main.JPG",
    type: "front-end",
  },
  {
    name: "FlowerLover",
    technologies: ["HTML", "SCSS", "Typescript", "Gulp", "Webpack"],
    link: "https://denisfriz.github.io/Flowers/",
    smallImg: "./img/FlowerLover_main.JPG",
    fullscreenImg: "./img/FlowerLover_fullscreen.png",
    type: "front-end",
  },
  {
    name: "HorseClub",
    technologies: ["HTML", "SCSS", "JS", "Webpack"],
    link: "https://denisfriz.github.io/HorseClub/",
    smallImg: "./img/HorseClub-main.JPG",
    fullscreenImg: "./img/HorseClub-fullscreen.png",
    type: "front-end",
  },
  {
    name: "Jadoo",
    technologies: ["HTML", "SCSS", "JS", "Gulp"],
    link: "https://denisfriz.github.io/Jadoo/",
    smallImg: "./img/Jadoo-main.JPG",
    fullscreenImg: "./img/Jadoo-fullscreen.png",
    type: "front-end",
  },
  {
    name: "London",
    technologies: ["HTML", "SCSS", "JS", "Bootstrap", "Webpack"],
    link: "https://denisfriz.github.io/London/",
    smallImg: "./img/London-main.JPG",
    fullscreenImg: "./img/London-fullscreen.png",
    type: "front-end",
  },
  {
    name: "Medical",
    technologies: ["HTML", "SASS", "JS", "Webpack"],
    link: "https://denisfriz.github.io/Medical/",
    smallImg: "./img/Medical-main.JPG",
    fullscreenImg: "./img/Medical-fullscreen.png",
    type: "front-end",
  },
  {
    name: "Movies",
    technologies: ["React", "RTK Query", "Typescript", "Material UI", "Vite"],
    link: "https://denisfriz.github.io/MovieDB/",
    smallImg: "./img/Movies-main.JPG",
    fullscreenImg: "./img/Movies-fullscreen.png",
    type: "front-end",
  },
  {
    name: "Organic",
    technologies: ["HTML", "SCSS", "JS", "Gulp"],
    link: "https://denisfriz.github.io/Organic/",
    smallImg: "./img/Organic-main.JPG",
    fullscreenImg: "./img/Organic-fullscreen.png",
    type: "front-end",
  },
  {
    name: "Helyfly",
    technologies: ["HTML", "SCSS", "JS", "Webpack"],
    link: "https://denisfriz.github.io/Helyfly/",
    smallImg: "./img/Helyfly-main.JPG",
    fullscreenImg: "./img/Helyfly-fullscreen.png",
    type: "front-end",
  },
  {
    name: "WPM (Words per minute)",
    technologies: ["HTML", "SCSS", "JS"],
    link: "https://denisfriz.github.io/WPM/",
    smallImg: "./img/WPM-main.JPG",
    fullscreenImg: "./img/WPM-fullscreen.png",
    type: "front-end",
  },
  {
    name: "Yoga",
    technologies: ["HTML", "SCSS", "JS", "Webpack"],
    link: "https://denisfriz.github.io/Yoga/",
    smallImg: "./img/Yoga-main.JPG",
    fullscreenImg: "./img/Yoga-fullscreen.png",
    type: "front-end",
  },
  {
    name: "AppLab",
    technologies: ["HTML", "SASS", "JS", "Webpack"],
    link: "https://denisfriz.github.io/AppLab/",
    smallImg: "./img/AppLab-main.JPG",
    fullscreenImg: "./img/AppLab-fullscreen.png",
    type: "front-end",
  },
  {
    name: "FakeSpotify",
    technologies: ["React", "RTK Query", "Typescript", "SCSS", "Vite"],
    link: "./video/FakeSpotify.mp4",
    smallImg: "",
    fullscreenImg: "",
    type: "Full Stack",
  },
  {
    name: "Quiz",
    technologies: ["React", "Typescript", "MUI", "Vite"],
    link: "./video/Quiz.mp4",
    smallImg: "",
    fullscreenImg: "",
    type: "Full Stack",
  },
  {
    name: "Vimo",
    technologies: [
      "React",
      "Redux",
      "Typescript",
      "MUI",
      "PostgreSql",
      "Node JS",
    ],
    link: "./video/Vimo.mp4",
    smallImg: "",
    fullscreenImg: "",
    type: "Full Stack",
  },
];
